#!/bin/sh

full=0
mod=0
while [ -n "$(echo $1 | grep '-')" ]; do
    case $1 in 
       -f ) full=1 ;;
       -m ) mod=1 ;;
       *  ) echo 'usage: vc [-f] [-m]'
            exit 1
    esac
    shift
done
LC_ALL=C
git --no-pager log -1 HEAD --pretty=format:"Hash: %H%nAbr. Hash: %h%nParent Hashes: %P%nAbr. Parent Hashes: %p%nAuthor Name: %an%nAuthor Email: %ae%nAuthor Date: %ai%nCommitter Name: %cn%nCommitter Email: %ce%nCommitter Date: %ci%n" |awk -v script=log -v full=$full -f vc-reporting/vc-git.awk > vc-reporting/vc.tex
if [ "$mod" = 1 ]
then
  git status |awk -v script=status -f vc-reporting/vc-git.awk >> vc-reporting/vc.tex
fi
